### ISSUE TITLE
notifications as a graphql sub so as to eliminate need for page refresh

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/directory-fe#129]

**Comment by Phanoix** [comment]
Since many departmental proxies seem to break websockets with load balancing involved, we should have a toggle to turn it off (either user interactive or just an system-only circuit breaker) in case it keeps spamming the server. This would get automatically toggled when the ws returns with a network error, or maybe retry + circuit breaker pattern (retry say in 1s, 2s, 4s, 8s, and if it still keeps erroring out then stop).

It can either be stored as a cookie or in the component’s state if we want it to try again on reload.
